// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import EditableTextController from "./editable_text_controller"
application.register("editable-text", EditableTextController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ScriptUpdateController from "./script_update_controller"
application.register("script-update", ScriptUpdateController)

import VideoPlayerController from "./video_player_controller"
application.register("video-player", VideoPlayerController)

import WordCloudController from "./word_cloud_controller"
application.register("word-cloud", WordCloudController)
