require "open-uri"

puts "Cleaning database..."
Script.destroy_all
User.destroy_all
Blueprint.destroy_all

puts "Creating Users..."

puts "Creating Test User..."

testuser = User.create!(
  email: "test@storylab.com",
  password: "123456"
)

puts "User with id :#{testuser.id} has been created"

puts "Creating Blueprints..."

comparison = Blueprint.create!(
  name: "Comparison",
  prompt_template: %Q{
    [INTRODUCTION]
Host (smiling, facing the camera): "Hey there, tech enthusiasts! Welcome back to our channel! Today, we have an exciting comparison that everyone's been waiting for. That's right, we'll be diving into the world of iPhones, pitting the legendary iPhone 12 against the newest sensation, the iPhone 13. So, without further ado, let's get started!"

[OPENING SHOT]
(Upbeat music starts, showcasing both iPhone 12 and iPhone 13 side by side on a table)

[SEGMENT 1: DESIGN & DISPLAY]
Host: "When it comes to design and display, the iPhone 12 set a high standard. But, the iPhone 13 takes it up a notch. With its Ceramic Shield front cover, it's four times more drop-resistant than the iPhone 12. And the colors, oh my! The iPhone 13 comes in stunning new shades, offering a refreshing change from the iPhone 12's color palette. Whether it's the Ceramic Blue, Pink Sand, or the classic Product(RED), you'll be spoilt for choice!"

[SEGMENT 2: PERFORMANCE]
Host: "Moving on to performance, the iPhone 13 is a beast! Powered by the A15 Bionic chip, it's faster and more efficient than ever before. Gamers, rejoice! The graphics performance on the iPhone 13 is mind-blowing. But don't underestimate the iPhone 12; it still packs a punch with its A14 Bionic chip, delivering smooth multitasking and excellent gaming experiences."

[SEGMENT 3: CAMERA CAPABILITIES]
Host: "Now, let's talk about the eyes of these devices, the camera. The iPhone 12 was a game-changer with its dual-camera setup, producing stunning photos and videos. However, the iPhone 13 takes it to the next level! With its enhanced Night mode, you'll capture breathtaking shots even in low light conditions. And the Cinematic mode? It's like having a professional filmmaker in your pocket!"

[SEGMENT 4: BATTERY LIFE]
Host: "Battery life is always a concern for heavy users, and Apple has listened. The iPhone 13 boasts impressive battery life, giving you hours of extra usage compared to the iPhone 12. You can now enjoy your favorite content without worrying about charging constantly."

[SEGMENT 5: 5G & CONNECTIVITY]
Host: "In today's world, connectivity matters more than ever. Both the iPhone 12 and iPhone 13 support 5G technology, ensuring blazing-fast download speeds and seamless video streaming. However, the iPhone 13 takes it a step further with its improved 5G capabilities, offering better coverage and faster connections in more places."

[CLOSING REMARKS]
Host: "Ladies and gentlemen, there you have it – a head-to-head comparison between the incredible iPhone 12 and the impressive iPhone 13. It's clear that Apple has once again raised the bar with their latest release. Whether you're considering an upgrade or buying your first iPhone, both devices have something unique to offer. It ultimately comes down to your preferences and budget. Don't forget to hit that like button and subscribe to our channel for more exciting tech content. Until next time, stay tuned and stay geeky!"

[ENDING SHOT]
(The host smiles and waves as the camera slowly zooms out. The logo and channel name appear on the screen.)

Host (voice-over): "Thanks for watching!"

[OUTRO]
(Upbeat music fades out, and the screen fades to black.)
    },
  sample_videos: ['vgZvlLkFeAs', '8UKikrUZg7Q', 'wmb5AmE4TUs']
)

puts "Blueprint with id :#{comparison.id} has been created"

puts "Creating Scripts..."

testscript = Script.create!(
  name: "TestScript",
  user_id: testuser.id,
  blueprint_id: comparison.id,
  topic: "TestTopic",
  script_body: "Some text here generated by AI",
  tone: "informative",
  duration: 10
)

puts "User with id :#{testscript.id} has been created"

puts "Finished!"
